### ISSUE TITLE
TypeError: cannot marshal 'collections.defaultdict objects

### ISSUE THREAD

**Issue by naitik-skyscend** [scripting/xml-rpc#21]
Got the above error when tried to read the binary field from the table.

I am using Python3.10 version to execute my script to read the data.

**Comment by scripting** [comment]
This looks like a problem you're having with the toolkit you're using.

**Comment by naitik-skyscend** [comment]
> This looks like a problem you're having with the toolkit you're using.

Hi @scripting thanks for the reply. So, is there any specific toolkit that I need to use? Because I checked each and every things but didn't work for me. Is there any solution to resolve this?

**Comment by tomm3w** [comment]
I am not aware of any problem, I will take a look at it.  Thanks for letting me know

**Comment by scripting** [comment]
I'm closing this thread now. ;-)
